// Generated by https://quicktype.io

export interface IUsuarios {
    isActive:    boolean;
    idea:        string;
    nombre:      string;
    email:       string;
    rol:         string;
    incidencias: Incidencia[];
}

export interface Incidencia {
    codigo:      string;
    descripcion: string;
    fecha:       string;
    status:      string;
}
